### ISSUE TITLE
Section 3.2: Clarify Cloud Gaming Requirements

### ISSUE THREAD

**Issue by xingri** [w3c/webrtc-nv-use-cases#114] opened 2023-06-23 21:23 UTC
Clarifying Cloud Gaming Requirements

**Comment by xingri** [comment] 2023-06-23 21:26
@aboba could you please give me an edit permission on working group meeting slides <https://docs.google.com/presentation/d/1lti3-GFsJ1iU2pXFjfSzeK8xyKj6Ohng9D6HndPNPLc/edit#slide=id.p>?

**Comment by aboba** [comment] 2023-06-24 03:04
Do you have a PR you'd like to discuss?

**Comment by xingri** [comment] 2023-06-25 06:08
Hi @aboba,
We are currently working on it and need some additional time for the internal consensus. So I will prepare a PR by next month meeting.

**Comment by xingri** [comment] 2023-06-26 17:20
@aboba thank you for allowing me to comment. Could I invite Alfred in Nvidia to the monthly call? We are in the process of registering him as a webrtc working group member as well.

**Comment by aboba** [comment] 2023-06-26 17:32
All participants in the WebRTC WG are allowed to contribute.  We'll set some time aside at the July interim to continue use cases discussions.

**Comment by xingri** [comment] 2023-06-26 17:36
@aboba  Thank you for the information.

**Comment by aboba** [comment] 2023-06-27 17:34
The state of the Game Streaming use case was discussed in [WEBRTCWG-2023-05-16  (Page 14)](https://lists.w3.org/Archives/Public/www-archive/2023May/att-0000/WEBRTCWG-2023-05-16.pdf#page=14)

Related: https://github.com/w3c/webrtc-nv-use-cases/issues/103

**Comment by aboba** [comment] 2023-06-27 17:59
@xingri To answer your question, one step might be for us to discuss requirements N37 and N38, as well as any other issues you have encountered in implementing this use case. We could then present a PR for the July meeting.

**Comment by xingri** [comment] 2023-06-28 00:08
@aboba  Sounds great, thank you for the feedback.

**Comment by xingri** [comment] 2023-07-13 00:04
@aboba  I have added PR(#118) and would like to present it on our next working group meeting.
Could you please arrange a time slot to discuss it about 5-10mins.

**Comment by aboba** [comment] 2023-07-13 03:13
I am going to close this issue since it appears to be a duplicate of https://github.com/w3c/webrtc-nv-use-cases/issues/103

**Closed by aboba** 2023-07-13 03:13 UTC
Labels: July 2023 Virtual Interim
